name: PR

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: npm run build

  code_formatting:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run format

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: |
          npx playwright install chromium
          npm run test

  examples:
    name: Examples
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: cd examples && npm run build
      - name: Lint
        run: cd examples && npm run lint
      - name: Prettier
        run: cd examples && npm run prettier
      - name: Test
        run: |
          cd examples
          npx playwright install chromium
          npm run test  
